### ISSUE TITLE
curry complemented function

### ISSUE THREAD

**Issue by sdevmaster** [yuhanz/ramda-php#1]
complement returns a function without parameters, so when curried, reflection thinks it has no parameters, and it gets called with only one parameter.
I am not using your lib, was only researching how other people solved that problem, just wanted to point that out.
Sample code: 
```
$isNotInArray = (R::$_complement)('in_array');
$AisNotInArray = R::curry($isNotInArray)('a');
var_dump($AisNotInArray);

```

**Comment by yuhanz** [comment]
works when the parameter inside R::$_complement being a function than a string. 

looks like there missed a test. has been added: https://github.com/yuhanz/ramda-php/blob/master/tests/WhereTest.php#L72

**Comment by sdevmaster** [comment]
No it does not:

$inArray = function($needle, $haystack){
    return in_array($needle, $haystack);
};

$isNotInArray = (R::$_complement)($inArray);
$AisNotInArray = R::curry($isNotInArray)('a');
var_dump($AisNotInArray);
var_dump($AisNotInArray(['a']));

The Problem is not the complement function, it is the curry function,, becuase it receives a function without arguments when complemented. The code above throws an error - that is not expected.
I won't add new comments to this issue if you don't want to understand, it is not my problem, i write such helpers by myself. Just wanted to help, because there is an error that is not that easy resolvable in php. I was explicitely looking for that error. 
BTW built-in function can only be referenced and called as string, and it works.

**Comment by yuhanz** [comment]
hi Steffen,

because the function _complement returns an anonymous function the reads in arguments at run time, the R::curry function couldn't figure out the correct number of arguments. If provided the call to the curry method with 2 arguments, this starts to work:

      $AisNotInArray = R::_curry2($isNotInArray)('a');
      $this->assertFalse($AisNotInArray(['a']));

I used R::$_{method_name} to be functions without curry, and apply R::${method_name} for function with curry enabled.

This issue also happened with $lift similarly; I wasn't able to find a work-around so I commented it out and left it unavailable. To be consistent, I unchecked the availability for method R::$complement, as it is not curry-enabled.

Thank you.
